### ISSUE TITLE
Can't install the node-red-contrib-modbus

### ISSUE THREAD

**Issue by mpous** [mpous/nodeRED-iiot-gateway#1]
After clicking install i get these logs:

```


-----------------------------------------------------------
2022-04-13T16:02:42.948Z Install : node-red-contrib-modbus 5.21.2

2022-04-13T16:02:43.814Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-modbus@5.21.2
2022-04-13T16:03:15.178Z [err] npm ERR! code 1
2022-04-13T16:03:15.178Z [err] npm ERR! path /data/node-red/user/node_modules/@serialport/bindings
2022-04-13T16:03:15.184Z [err] npm ERR!
2022-04-13T16:03:15.184Z [err]  command failed
2022-04-13T16:03:15.184Z [err] npm ERR! command sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2022-04-13T16:03:15.185Z [err] npm ERR! prebuild-install WARN install No prebuilt binaries found (target=17.7.2 runtime=node arch=arm libc= platform=linux)
2022-04-13T16:03:15.185Z [err] npm ERR! gyp info it worked if it ends with ok
2022-04-13T16:03:15.185Z [err] npm 
2022-04-13T16:03:15.186Z [err] ERR! gyp info using node-gyp@8.4.1
2022-04-13T16:03:15.186Z [err] npm ERR! gyp info using node@17.7.2 | linux | arm
2022-04-13T16:03:15.186Z [err] npm ERR! gyp info find Python using Python version 3.9.6 found at "/usr/local/bin/python3"
2022-04-13T16:03:15.186Z [err] npm ERR!
2022-04-13T16:03:15.186Z [err]  gyp http GET https://nodejs.org/download/release/v17.7.2/node-v17.7.2-headers.tar.gz
2022-04-13T16:03:15.186Z [err] npm ERR! gyp http 200 https://nodejs.org/download/release/v17.7.2/node-v17.7.2-headers.tar.gz
2022-04-13T16:03:15.186Z [err] npm ERR! gyp http GET https://nodejs.org/download/release/v17.7.2/SHASUMS256.txt
2022-04-13T16:03:15.186Z [err] npm 
2022-04-13T16:03:15.186Z [err] ERR! gyp http 200 https://nodejs.org/download/release/v17.7.2/SHASUMS256.txt
2022-04-13T16:03:15.186Z [err] npm ERR! gyp info spawn /usr/local/bin/python3
2022-04-13T16:03:15.186Z [err] npm ERR!
2022-04-13T16:03:15.187Z [err]  gyp info spawn args [
2022-04-13T16:03:15.187Z [err] npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2022-04-13T16:03:15.187Z [err] npm ERR! gyp info spawn args   'binding.gyp',
2022-04-13T16:03:15.187Z [err] npm 
2022-04-13T16:03:15.188Z [err] ERR! gyp info spawn args   '-f',
2022-04-13T16:03:15.188Z [err] npm ERR! gyp info spawn args   'make',
2022-04-13T16:03:15.188Z [err] npm ERR! gyp info spawn args   '-I',
2022-04-13T16:03:15.188Z [err] npm ERR! gyp info spawn args   '/data/node-red/user/node_modules/@serialport/bindings/build/config.gypi',
2022-04-13T16:03:15.188Z [err] npm ERR! gyp info spawn args   '-I',
2022-04-13T16:03:15.188Z [err] npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2022-04-13T16:03:15.188Z [err] npm ERR! gyp info spawn args   '-I',
2022-04-13T16:03:15.188Z [err] npm ERR!
2022-04-13T16:03:15.188Z [err]  gyp info spawn args   '/root/.cache/node-gyp/17.7.2/include/node/common.gypi',
2022-04-13T16:03:15.188Z [err] npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
2022-04-13T16:03:15.188Z [err] npm ERR! gyp info spawn args   '-Dvisibility=default',
2022-04-13T16:03:15.188Z [err] npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/17.7.2',
2022-04-13T16:03:15.188Z [err] npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
2022-04-13T16:03:15.189Z [err] npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/17.7.2/<(target_arch)/node.lib',
2022-04-13T16:03:15.189Z [err] npm ERR! gyp info spawn args   '-Dmodule_root_dir=/data/node-red/user/node_modules/@serialport/bindings',
2022-04-13T16:03:15.189Z [err] npm ERR! gyp info spawn args   '-Dnode_engine=v8',
2022-04-13T16:03:15.189Z [err] npm ERR!
2022-04-13T16:03:15.189Z [err]  gyp info spawn args   '--depth=.',
2022-04-13T16:03:15.189Z [err] npm ERR! gyp info spawn args   '--no-parallel',
2022-04-13T16:03:15.189Z [err] npm ERR! gyp info spawn args   '--generator-output',
2022-04-13T16:03:15.189Z [err] npm ERR! gyp info spawn args   'build',
2022-04-13T16:03:15.189Z [err] npm ERR! gyp info spawn args   '-Goutput_dir=.'
2022-04-13T16:03:15.190Z [err] npm ERR! gyp info spawn args ]
2022-04-13T16:03:15.190Z [err] npm ERR! gyp ERR! build error 
2022-04-13T16:03:15.190Z [err] npm ERR!
2022-04-13T16:03:15.190Z [err]  gyp ERR! stack Error: not found: make
2022-04-13T16:03:15.190Z [err] npm ERR! gyp ERR! stack     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:10:17)
2022-04-13T16:03:15.190Z [err] npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:57:18
2022-04-13T16:03:15.190Z [err] npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
2022-04-13T16:03:15.190Z [err] npm
2022-04-13T16:03:15.191Z [err]  ERR! gyp ERR! stack     at step (/usr/local/lib/node_modules/npm/node_modules/which/which.js:54:21)
2022-04-13T16:03:15.191Z [err] npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:71:22
2022-04-13T16:03:15.191Z [err] npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
2022-04-13T16:03:15.191Z [err] npm ERR!
2022-04-13T16:03:15.191Z [err]  gyp ERR! stack     at subStep (/usr/local/lib/node_modules/npm/node_modules/which/which.js:69:33)
2022-04-13T16:03:15.191Z [err] npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:80:22
2022-04-13T16:03:15.191Z [err] npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2022-04-13T16:03:15.192Z [err] npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2022-04-13T16:03:15.192Z [err] npm ERR! gyp ERR! System Linux 5.10.83-v8
2022-04-13T16:03:15.192Z [err] npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2022-04-13T16:03:15.192Z [err] npm ERR! gyp ERR! cwd /data/node-red/user/node_modules/@serialport/bindings
2022-04-13T16:03:15.192Z [err] npm ERR!
2022-04-13T16:03:15.192Z [err]  gyp ERR! node -v v17.7.2
2022-04-13T16:03:15.192Z [err] npm ERR! gyp ERR! node-gyp -v v8.4.1
2022-04-13T16:03:15.192Z [err] npm ERR! gyp ERR! not ok
2022-04-13T16:03:15.198Z [err] 
2022-04-13T16:03:15.199Z [err] npm ERR!
2022-04-13T16:03:15.199Z [err]  A complete log of this run can be found in:
2022-04-13T16:03:15.199Z [err] npm ERR!     /root/.npm/_logs/2022-04-13T16_02_44_532Z-debug-0.log
2022-04-13T16:03:15.239Z rc=1

```

**Comment by biancode** [comment]
use NodeJS v16 or less - v17 is not supported for now - there are problems with the serialport and other 3rd modules.
